package it.dsigno.liferay.sb.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import it.dsigno.liferay.sb.model.Logger;
import it.dsigno.liferay.sb.service.LoggerLocalServiceUtil;

/**
 * The extended model base implementation for the Logger service. Represents a row in the &quot;IT_DSIGNO_Logger&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LoggerImpl}.
 * </p>
 *
 * @author @denissignoretto
 * @see LoggerImpl
 * @see it.dsigno.liferay.sb.model.Logger
 * @generated
 */
public abstract class LoggerBaseImpl extends LoggerModelImpl implements Logger {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a logger model instance should use the {@link Logger} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            LoggerLocalServiceUtil.addLogger(this);
        } else {
            LoggerLocalServiceUtil.updateLogger(this);
        }
    }
}
