package it.dsigno.liferay.sb.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import it.dsigno.liferay.sb.model.Logger;
import it.dsigno.liferay.sb.model.LoggerModel;
import it.dsigno.liferay.sb.model.LoggerSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Logger service. Represents a row in the &quot;IT_DSIGNO_Logger&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link it.dsigno.liferay.sb.model.LoggerModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LoggerImpl}.
 * </p>
 *
 * @author @denissignoretto
 * @see LoggerImpl
 * @see it.dsigno.liferay.sb.model.Logger
 * @see it.dsigno.liferay.sb.model.LoggerModel
 * @generated
 */
@JSON(strict = true)
public class LoggerModelImpl extends BaseModelImpl<Logger>
    implements LoggerModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a logger model instance should use the {@link it.dsigno.liferay.sb.model.Logger} interface instead.
     */
    public static final String TABLE_NAME = "IT_DSIGNO_Logger";
    public static final Object[][] TABLE_COLUMNS = {
            { "loggerId", Types.BIGINT },
            { "groupId", Types.BIGINT },
            { "companyId", Types.BIGINT },
            { "userId", Types.BIGINT },
            { "userName", Types.VARCHAR },
            { "createDate", Types.TIMESTAMP },
            { "modifiedDate", Types.TIMESTAMP },
            { "logMessage", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table IT_DSIGNO_Logger (loggerId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,logMessage VARCHAR(75) null)";
    public static final String TABLE_SQL_DROP = "drop table IT_DSIGNO_Logger";
    public static final String ORDER_BY_JPQL = " ORDER BY logger.loggerId ASC";
    public static final String ORDER_BY_SQL = " ORDER BY IT_DSIGNO_Logger.loggerId ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.it.dsigno.liferay.sb.model.Logger"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.it.dsigno.liferay.sb.model.Logger"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.it.dsigno.liferay.sb.model.Logger"));
    private static ClassLoader _classLoader = Logger.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] { Logger.class };
    private long _loggerId;
    private long _groupId;
    private long _companyId;
    private long _userId;
    private String _userUuid;
    private String _userName;
    private Date _createDate;
    private Date _modifiedDate;
    private String _logMessage;
    private Logger _escapedModel;

    public LoggerModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static Logger toModel(LoggerSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        Logger model = new LoggerImpl();

        model.setLoggerId(soapModel.getLoggerId());
        model.setGroupId(soapModel.getGroupId());
        model.setCompanyId(soapModel.getCompanyId());
        model.setUserId(soapModel.getUserId());
        model.setUserName(soapModel.getUserName());
        model.setCreateDate(soapModel.getCreateDate());
        model.setModifiedDate(soapModel.getModifiedDate());
        model.setLogMessage(soapModel.getLogMessage());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<Logger> toModels(LoggerSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<Logger> models = new ArrayList<Logger>(soapModels.length);

        for (LoggerSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _loggerId;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setLoggerId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _loggerId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Logger.class;
    }

    @Override
    public String getModelClassName() {
        return Logger.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("loggerId", getLoggerId());
        attributes.put("groupId", getGroupId());
        attributes.put("companyId", getCompanyId());
        attributes.put("userId", getUserId());
        attributes.put("userName", getUserName());
        attributes.put("createDate", getCreateDate());
        attributes.put("modifiedDate", getModifiedDate());
        attributes.put("logMessage", getLogMessage());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long loggerId = (Long) attributes.get("loggerId");

        if (loggerId != null) {
            setLoggerId(loggerId);
        }

        Long groupId = (Long) attributes.get("groupId");

        if (groupId != null) {
            setGroupId(groupId);
        }

        Long companyId = (Long) attributes.get("companyId");

        if (companyId != null) {
            setCompanyId(companyId);
        }

        Long userId = (Long) attributes.get("userId");

        if (userId != null) {
            setUserId(userId);
        }

        String userName = (String) attributes.get("userName");

        if (userName != null) {
            setUserName(userName);
        }

        Date createDate = (Date) attributes.get("createDate");

        if (createDate != null) {
            setCreateDate(createDate);
        }

        Date modifiedDate = (Date) attributes.get("modifiedDate");

        if (modifiedDate != null) {
            setModifiedDate(modifiedDate);
        }

        String logMessage = (String) attributes.get("logMessage");

        if (logMessage != null) {
            setLogMessage(logMessage);
        }
    }

    @JSON
    @Override
    public long getLoggerId() {
        return _loggerId;
    }

    @Override
    public void setLoggerId(long loggerId) {
        _loggerId = loggerId;
    }

    @JSON
    @Override
    public long getGroupId() {
        return _groupId;
    }

    @Override
    public void setGroupId(long groupId) {
        _groupId = groupId;
    }

    @JSON
    @Override
    public long getCompanyId() {
        return _companyId;
    }

    @Override
    public void setCompanyId(long companyId) {
        _companyId = companyId;
    }

    @JSON
    @Override
    public long getUserId() {
        return _userId;
    }

    @Override
    public void setUserId(long userId) {
        _userId = userId;
    }

    @Override
    public String getUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
    }

    @Override
    public void setUserUuid(String userUuid) {
        _userUuid = userUuid;
    }

    @JSON
    @Override
    public String getUserName() {
        if (_userName == null) {
            return StringPool.BLANK;
        } else {
            return _userName;
        }
    }

    @Override
    public void setUserName(String userName) {
        _userName = userName;
    }

    @JSON
    @Override
    public Date getCreateDate() {
        return _createDate;
    }

    @Override
    public void setCreateDate(Date createDate) {
        _createDate = createDate;
    }

    @JSON
    @Override
    public Date getModifiedDate() {
        return _modifiedDate;
    }

    @Override
    public void setModifiedDate(Date modifiedDate) {
        _modifiedDate = modifiedDate;
    }

    @JSON
    @Override
    public String getLogMessage() {
        if (_logMessage == null) {
            return StringPool.BLANK;
        } else {
            return _logMessage;
        }
    }

    @Override
    public void setLogMessage(String logMessage) {
        _logMessage = logMessage;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
            Logger.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Logger toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Logger) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        LoggerImpl loggerImpl = new LoggerImpl();

        loggerImpl.setLoggerId(getLoggerId());
        loggerImpl.setGroupId(getGroupId());
        loggerImpl.setCompanyId(getCompanyId());
        loggerImpl.setUserId(getUserId());
        loggerImpl.setUserName(getUserName());
        loggerImpl.setCreateDate(getCreateDate());
        loggerImpl.setModifiedDate(getModifiedDate());
        loggerImpl.setLogMessage(getLogMessage());

        loggerImpl.resetOriginalValues();

        return loggerImpl;
    }

    @Override
    public int compareTo(Logger logger) {
        long primaryKey = logger.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Logger)) {
            return false;
        }

        Logger logger = (Logger) obj;

        long primaryKey = logger.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<Logger> toCacheModel() {
        LoggerCacheModel loggerCacheModel = new LoggerCacheModel();

        loggerCacheModel.loggerId = getLoggerId();

        loggerCacheModel.groupId = getGroupId();

        loggerCacheModel.companyId = getCompanyId();

        loggerCacheModel.userId = getUserId();

        loggerCacheModel.userName = getUserName();

        String userName = loggerCacheModel.userName;

        if ((userName != null) && (userName.length() == 0)) {
            loggerCacheModel.userName = null;
        }

        Date createDate = getCreateDate();

        if (createDate != null) {
            loggerCacheModel.createDate = createDate.getTime();
        } else {
            loggerCacheModel.createDate = Long.MIN_VALUE;
        }

        Date modifiedDate = getModifiedDate();

        if (modifiedDate != null) {
            loggerCacheModel.modifiedDate = modifiedDate.getTime();
        } else {
            loggerCacheModel.modifiedDate = Long.MIN_VALUE;
        }

        loggerCacheModel.logMessage = getLogMessage();

        String logMessage = loggerCacheModel.logMessage;

        if ((logMessage != null) && (logMessage.length() == 0)) {
            loggerCacheModel.logMessage = null;
        }

        return loggerCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(17);

        sb.append("{loggerId=");
        sb.append(getLoggerId());
        sb.append(", groupId=");
        sb.append(getGroupId());
        sb.append(", companyId=");
        sb.append(getCompanyId());
        sb.append(", userId=");
        sb.append(getUserId());
        sb.append(", userName=");
        sb.append(getUserName());
        sb.append(", createDate=");
        sb.append(getCreateDate());
        sb.append(", modifiedDate=");
        sb.append(getModifiedDate());
        sb.append(", logMessage=");
        sb.append(getLogMessage());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(28);

        sb.append("<model><model-name>");
        sb.append("it.dsigno.liferay.sb.model.Logger");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>loggerId</column-name><column-value><![CDATA[");
        sb.append(getLoggerId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>groupId</column-name><column-value><![CDATA[");
        sb.append(getGroupId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>companyId</column-name><column-value><![CDATA[");
        sb.append(getCompanyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userId</column-name><column-value><![CDATA[");
        sb.append(getUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userName</column-name><column-value><![CDATA[");
        sb.append(getUserName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>createDate</column-name><column-value><![CDATA[");
        sb.append(getCreateDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
        sb.append(getModifiedDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>logMessage</column-name><column-value><![CDATA[");
        sb.append(getLogMessage());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
