package it.dsigno.liferay.sb.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import it.dsigno.liferay.sb.model.Logger;
import it.dsigno.liferay.sb.service.LoggerService;
import it.dsigno.liferay.sb.service.persistence.LoggerPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the logger remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link it.dsigno.liferay.sb.service.impl.LoggerServiceImpl}.
 * </p>
 *
 * @author @denissignoretto
 * @see it.dsigno.liferay.sb.service.impl.LoggerServiceImpl
 * @see it.dsigno.liferay.sb.service.LoggerServiceUtil
 * @generated
 */
public abstract class LoggerServiceBaseImpl extends BaseServiceImpl
    implements LoggerService, IdentifiableBean {
    @BeanReference(type = it.dsigno.liferay.sb.service.LoggerLocalService.class)
    protected it.dsigno.liferay.sb.service.LoggerLocalService loggerLocalService;
    @BeanReference(type = it.dsigno.liferay.sb.service.LoggerService.class)
    protected it.dsigno.liferay.sb.service.LoggerService loggerService;
    @BeanReference(type = LoggerPersistence.class)
    protected LoggerPersistence loggerPersistence;
    @BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
    protected com.liferay.counter.service.CounterLocalService counterLocalService;
    @BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
    protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
    @BeanReference(type = com.liferay.portal.service.UserLocalService.class)
    protected com.liferay.portal.service.UserLocalService userLocalService;
    @BeanReference(type = com.liferay.portal.service.UserService.class)
    protected com.liferay.portal.service.UserService userService;
    @BeanReference(type = UserPersistence.class)
    protected UserPersistence userPersistence;
    private String _beanIdentifier;
    private ClassLoader _classLoader;
    private LoggerServiceClpInvoker _clpInvoker = new LoggerServiceClpInvoker();

    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. Always use {@link it.dsigno.liferay.sb.service.LoggerServiceUtil} to access the logger remote service.
     */

    /**
     * Returns the logger local service.
     *
     * @return the logger local service
     */
    public it.dsigno.liferay.sb.service.LoggerLocalService getLoggerLocalService() {
        return loggerLocalService;
    }

    /**
     * Sets the logger local service.
     *
     * @param loggerLocalService the logger local service
     */
    public void setLoggerLocalService(
        it.dsigno.liferay.sb.service.LoggerLocalService loggerLocalService) {
        this.loggerLocalService = loggerLocalService;
    }

    /**
     * Returns the logger remote service.
     *
     * @return the logger remote service
     */
    public it.dsigno.liferay.sb.service.LoggerService getLoggerService() {
        return loggerService;
    }

    /**
     * Sets the logger remote service.
     *
     * @param loggerService the logger remote service
     */
    public void setLoggerService(
        it.dsigno.liferay.sb.service.LoggerService loggerService) {
        this.loggerService = loggerService;
    }

    /**
     * Returns the logger persistence.
     *
     * @return the logger persistence
     */
    public LoggerPersistence getLoggerPersistence() {
        return loggerPersistence;
    }

    /**
     * Sets the logger persistence.
     *
     * @param loggerPersistence the logger persistence
     */
    public void setLoggerPersistence(LoggerPersistence loggerPersistence) {
        this.loggerPersistence = loggerPersistence;
    }

    /**
     * Returns the counter local service.
     *
     * @return the counter local service
     */
    public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
        return counterLocalService;
    }

    /**
     * Sets the counter local service.
     *
     * @param counterLocalService the counter local service
     */
    public void setCounterLocalService(
        com.liferay.counter.service.CounterLocalService counterLocalService) {
        this.counterLocalService = counterLocalService;
    }

    /**
     * Returns the resource local service.
     *
     * @return the resource local service
     */
    public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
        return resourceLocalService;
    }

    /**
     * Sets the resource local service.
     *
     * @param resourceLocalService the resource local service
     */
    public void setResourceLocalService(
        com.liferay.portal.service.ResourceLocalService resourceLocalService) {
        this.resourceLocalService = resourceLocalService;
    }

    /**
     * Returns the user local service.
     *
     * @return the user local service
     */
    public com.liferay.portal.service.UserLocalService getUserLocalService() {
        return userLocalService;
    }

    /**
     * Sets the user local service.
     *
     * @param userLocalService the user local service
     */
    public void setUserLocalService(
        com.liferay.portal.service.UserLocalService userLocalService) {
        this.userLocalService = userLocalService;
    }

    /**
     * Returns the user remote service.
     *
     * @return the user remote service
     */
    public com.liferay.portal.service.UserService getUserService() {
        return userService;
    }

    /**
     * Sets the user remote service.
     *
     * @param userService the user remote service
     */
    public void setUserService(
        com.liferay.portal.service.UserService userService) {
        this.userService = userService;
    }

    /**
     * Returns the user persistence.
     *
     * @return the user persistence
     */
    public UserPersistence getUserPersistence() {
        return userPersistence;
    }

    /**
     * Sets the user persistence.
     *
     * @param userPersistence the user persistence
     */
    public void setUserPersistence(UserPersistence userPersistence) {
        this.userPersistence = userPersistence;
    }

    public void afterPropertiesSet() {
        Class<?> clazz = getClass();

        _classLoader = clazz.getClassLoader();
    }

    public void destroy() {
    }

    /**
     * Returns the Spring bean ID for this bean.
     *
     * @return the Spring bean ID for this bean
     */
    @Override
    public String getBeanIdentifier() {
        return _beanIdentifier;
    }

    /**
     * Sets the Spring bean ID for this bean.
     *
     * @param beanIdentifier the Spring bean ID for this bean
     */
    @Override
    public void setBeanIdentifier(String beanIdentifier) {
        _beanIdentifier = beanIdentifier;
    }

    @Override
    public Object invokeMethod(String name, String[] parameterTypes,
        Object[] arguments) throws Throwable {
        Thread currentThread = Thread.currentThread();

        ClassLoader contextClassLoader = currentThread.getContextClassLoader();

        if (contextClassLoader != _classLoader) {
            currentThread.setContextClassLoader(_classLoader);
        }

        try {
            return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
        } finally {
            if (contextClassLoader != _classLoader) {
                currentThread.setContextClassLoader(contextClassLoader);
            }
        }
    }

    protected Class<?> getModelClass() {
        return Logger.class;
    }

    protected String getModelClassName() {
        return Logger.class.getName();
    }

    /**
     * Performs an SQL query.
     *
     * @param sql the sql query
     */
    protected void runSQL(String sql) throws SystemException {
        try {
            DataSource dataSource = loggerPersistence.getDataSource();

            SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
                    sql, new int[0]);

            sqlUpdate.update();
        } catch (Exception e) {
            throw new SystemException(e);
        }
    }
}
